// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox') // IMPORTANTE: Añadir esto
const assert = require('assert')

describe('anadirsaldo', function() {
  this.timeout(30000)
  let driver
  let vars
  
  beforeEach(async function() {
    // Configuración Headless para que no falle en Linux/WSL
    const options = new firefox.Options().addArguments('--headless')
    
    driver = await new Builder()
        .forBrowser('firefox')
        .setFirefoxOptions(options)
        .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) {
      await driver.quit();
    }
  })

  it('anadirsaldo', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    
    // --- LOGIN ---
    await driver.findElement(By.css(".ghost")).click()
    // Esperamos un poco a que la animación del formulario termine si es necesario
    await driver.wait(until.elementLocated(By.css("label:nth-child(1) > input")), 5000)
    
    await driver.findElement(By.css("label:nth-child(1) > input")).click()
    await driver.findElement(By.css("label:nth-child(1) > input")).sendKeys("pedrito@gmail.com")
    await driver.findElement(By.css("label:nth-child(2) > input")).click()
    await driver.findElement(By.css("label:nth-child(2) > input")).sendKeys("Pedrito")
    
    // Click en Login
    await driver.findElement(By.css("button")).click()

    // --- AQUÍ FALLABA ---
    // Solución: Esperamos hasta 10 segundos a que aparezca el elemento tras el login
    const botonAcciones = await driver.wait(
        until.elementLocated(By.css(".actions > .small")), 
        10000 // Tiempo máximo de espera en ms
    );
    // A veces está localizado pero no "clickable" aún, esperamos a que sea visible
    await driver.wait(until.elementIsVisible(botonAcciones), 10000);
    
    await botonAcciones.click()

    // --- RESTO DEL TEST ---
    // Es buena práctica esperar también aquí si la acción anterior carga algo nuevo
    const saldo = await driver.wait(until.elementLocated(By.css(".saldo")), 5000);
    await saldo.click()
    
    await driver.findElement(By.css("input")).sendKeys("1")
    // ... el resto de tu código sigue igual ...
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("2")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("3")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("4")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("5")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("6")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("7")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("8")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("9")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("10")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".btn-pay")).click()
  })
})