// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox')

describe('anadirsaldo', function() {
  this.timeout(60000) // 60 segundos de margen total
  let driver
  let vars

  beforeEach(async function() {
    // Configuración para entorno CI (Headless)
    const options = new firefox.Options()
      .addArguments('--headless')
      .addArguments('--width=1920')
      .addArguments('--height=1080');

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) {
      await driver.quit();
    }
  })

  it('anadirsaldo', async function() {
    // 1. Navegar a la web (Localhost porque el CI ya lo tiene levantado)
    await driver.get("http://localhost:5173/")
    
    // 2. Esperar y abrir Login
    await driver.wait(until.elementLocated(By.css(".ghost")), 10000);
    await driver.findElement(By.css(".ghost")).click()
    
    // 3. Rellenar Email (Uso estándar de Selenium)
    // Esperamos a que el input aparezca
    await driver.wait(until.elementLocated(By.css("label:nth-child(1) > input")), 5000);
    const emailInput = await driver.findElement(By.css("label:nth-child(1) > input"));
    await emailInput.click();
    await emailInput.clear(); // Limpiamos por si acaso
    await emailInput.sendKeys("pedrito@gmail.com");
    
    // 4. Rellenar Contraseña
    const passInput = await driver.findElement(By.css("label:nth-child(2) > input"));
    await passInput.click();
    await passInput.clear();
    await passInput.sendKeys("Pedrito");
    
    // 5. Entrar
    await driver.findElement(By.css("button")).click()

    // 6. Esperar transición al Dashboard
    // Buscamos el botón de ".actions > .small" que indica que estamos dentro
    const botonAcciones = await driver.wait(
        until.elementLocated(By.css(".actions > .small")), 
        15000 
    );
    // Aseguramos que sea visible y clickeable antes de interactuar
    await driver.wait(until.elementIsVisible(botonAcciones), 5000);
    await botonAcciones.click();

    // --- LÓGICA DE AÑADIR SALDO ---
    const saldo = await driver.wait(until.elementLocated(By.css(".saldo")), 5000);
    await saldo.click()
    
    // Secuencia de inputs y doble clicks
    await driver.findElement(By.css("input")).sendKeys("1")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("2")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("3")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("4")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("5")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("6")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("7")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("8")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("input")).sendKeys("9")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("10")
    await driver.findElement(By.css("input")).click()
    {
      const element = await driver.findElement(By.css("input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    
    // Finalizar pago
    await driver.findElement(By.css(".btn-pay")).click()
  })
})