// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

beforeEach(async function() {
  const options = new firefox.Options().headless()
  driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()
})

afterEach(async function() {
  if (driver) {
    await driver.quit()
  }
})


describe('login, panel administrador, borrar usuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login, panel administrador, borrar usuario', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    {
      const element = await driver.findElement(By.css(".home"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".home"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".home")).click()
    await driver.findElement(By.css(".ghost")).click()
    await driver.findElement(By.css("label:nth-child(1) > input")).click()
    await driver.findElement(By.css("label:nth-child(1) > input")).sendKeys("administrador@admin")
    await driver.findElement(By.css("label:nth-child(2) > input")).sendKeys("admin")
    await driver.findElement(By.css("label:nth-child(2) > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".actions > .btn:nth-child(2)")).click()
    await driver.findElement(By.css("tr:nth-child(6) .danger")).click()
    assert(await driver.switchTo().alert().getText() == "¿Seguro que deseas eliminar este usuario?")
    await driver.switchTo().alert().accept()
  })
})