// Generated by Selenium IDE
const { Builder, By, Key } = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox')
const assert = require('assert')

describe('loginbuscarunirmesuscripcion', function() {
  this.timeout(60000) // 60s por si tarda un poco en CI
  let driver
  let vars

  beforeEach(async function() {
    const options = new firefox.Options().addArguments('--headless')

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()

    vars = {}
  })

  afterEach(async function() {
    if (driver) {
      await driver.quit()
    }
  })

  it('loginbuscarunirmesuscripcion', async function() {
    await driver.get('http://localhost:5173/')
    await driver.manage().window().setRect({ width: 937, height: 922 })

    await driver.findElement(By.css('.ghost')).click()
    await driver.findElement(By.css('label:nth-child(1) > input')).click()
    await driver.findElement(By.css('label:nth-child(1) > input')).sendKeys('pedrito@gmail.com')
    await driver.findElement(By.css('label:nth-child(2) > input')).sendKeys('Pedrito')
    await driver.findElement(By.css('label:nth-child(2) > input')).sendKeys(Key.ENTER)
    await driver.findElement(By.css('.card:nth-child(1) .btn')).click()
    await driver.findElement(By.css('.plataforma-card:nth-child(1) > .btn')).click()
    await driver.findElement(By.css('.card-plan:nth-child(3) .btn-glossy')).click()

    const text = await driver.switchTo().alert().getText()
    assert(text === 'Ya eres miembro de este grupo')
    await driver.switchTo().alert().accept()
  })
})