// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox')
const assert = require('assert')

describe('Login,cuenta y crear grupo', function() {
  this.timeout(30000)

  /** @type {import('selenium-webdriver').WebDriver} */
  let driver
  let vars

  beforeEach(async function() {
    const options = new firefox.Options().addArguments('--headless')

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()

    vars = {}
  })

  afterEach(async function() {
    if (driver) {
      await driver.quit()
    }
  })

  it('Login,cuenta y crear grupo', async function() {
    await driver.get('http://localhost:5173/')
    await driver.manage().window().setRect({ width: 1936, height: 1048 })

    await driver.findElement(By.css('.ghost')).click()
    await driver.findElement(By.css('.primary:nth-child(1)')).click()
    await driver.findElement(By.css('.icon')).click()
    await driver.findElement(By.css('.input')).click()
    await driver.findElement(By.css('.input')).sendKeys('grupo oscar')
    await driver.findElement(By.css('.success')).click()
  })
})
