// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox')
const assert = require('assert')

describe('Login, buscar y unirme a grupo', function() {
  this.timeout(30000)

  /** @type {import('selenium-webdriver').WebDriver} */
  let driver
  let vars

  beforeEach(async function() {
    const options = new firefox.Options().addArguments('--headless')

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()

    vars = {}
  })

  afterEach(async function() {
    if (driver) {
      await driver.quit()
    }
  })

  it('Login, buscar y unirme a grupo', async function() {
    await driver.get('http://localhost:5173/')
    await driver.manage().window().setRect({ width: 1936, height: 1048 })

    await driver.findElement(By.css('.ghost')).click()
    await driver.findElement(By.css('label:nth-child(1) > input')).click()
    await driver.findElement(By.css('label:nth-child(1) > input')).sendKeys('oscar@gmail.com')
    await driver.findElement(By.css('label:nth-child(2) > input')).sendKeys('oscar')
    await driver.findElement(By.css('button')).click()
    await driver.findElement(By.css('.card:nth-child(1) .btn')).click()
    await driver.findElement(By.css('.plataforma-card:nth-child(1) > .btn')).click()
    await driver.findElement(By.css('.card-plan:nth-child(2) .btn-glossy')).click()

    const alertText = await driver.switchTo().alert().getText()
    assert.strictEqual(alertText, 'Te has unido al grupo correctamente')
  })
})
